---
title: "Blog 1 - Analysis"
author: "June Park"
date: '2022-09-15'
output: pdf_document
categories: []
tags: []
slug: []
---

This week, I looked at the Republican/Democrat voteshare margin of House congressional elections. I analyzed the 2018 and 2014 congressional elections.

```{r, include = FALSE}
# hide stuff
knitr::opts_chunk$set(echo = FALSE)

# libraries
library(tidyverse)
library(ggplot2)
library(usmap)
library(rmapshaper)
library(sf)
library(blogdown)

# data
housepartyvote <- read_csv("house party vote share by district 1948-2020.csv")
```

```{r, include = FALSE}
# Dataset of 2018 voteshare margin
house2016 <- housepartyvote %>%
  filter(raceYear == 2016) %>%
  select(raceYear, State, district_num, district_id, RepVotes, DemVotes) %>%
  # summarize party vote share by state
  group_by(State) %>%
  # create Votemargin
  mutate(Votemargin = (sum(RepVotes - DemVotes))/sum(RepVotes + DemVotes)) %>%
  rename(state = State)

house2018 <- housepartyvote %>%
  filter(raceYear == 2018) %>%
  select(raceYear, State, district_num, district_id, RepVotes, DemVotes) %>%
  # summarize party vote share by state
  group_by(State) %>%
  # create Votemargin
  mutate(Votemargin = (sum(RepVotes - DemVotes))/sum(RepVotes + DemVotes)) %>%
  rename(state = State)
```

```{r}
# Plot of 2016 voteshare margin
plot_usmap(data = house2016, 
           regions = "states", 
           values = "Votemargin",
           labels = TRUE) +
  scale_fill_gradient2(low = "skyblue3", 
                       mid = "white",
                       high = "firebrick3", 
                       name = "Two-party \nVoteshare Margin") +
  labs(title = "2016 Two-Party Voteshare Margin") +
  theme_void()

# Plot of 2018 voteshare margin
plot_usmap(data = house2018, 
           regions = "states", 
           values = "Votemargin",
           labels = TRUE) +
  scale_fill_gradient2(low = "skyblue3", 
                       mid = "white",
                       high = "firebrick3", 
                       name = "Two-party \nVoteshare Margin") +
  labs(title = "2018 Two-Party Voteshare Margin") +
  theme_void()
```


```{r, include = FALSE}
# Load geographic data for 114th congress - 2014 election
get_congress_map <- function(cong=114) {
  tmp_file <- tempfile()
  tmp_dir <- tempdir()
  zp <- sprintf("https://cdmaps.polisci.ucla.edu/shp/districts114.zip",cong)
  download.file(zp, tmp_file)
  unzip(zipfile = tmp_file, exdir = tmp_dir)
  fpath <- paste(tmp_dir, sprintf("districtShapes/districts114.shp",cong), sep = "/")
  st_read(fpath)
}

# Load 114th congress
cd114 <- get_congress_map(114)

# Find vote-share margins for the 2014 election
district2014 <- housepartyvote %>%
  filter(raceYear == 2014) %>%
  mutate(voteshare_margin = (RepVotes - DemVotes)/(RepVotes + DemVotes)) %>%
  select(raceYear, State, district_num, district_id, voteshare_margin) %>%
  mutate(DISTRICT = as.character(district_num)) %>%
  rename(STATENAME = State)
  
simplified_cd114 <- left_join(district2014, cd114, by = c("STATENAME", "DISTRICT")) %>%
  filter(!STATENAME %in% c("Alaska","Hawaii")) %>%
  st_as_sf() %>%
  st_transform("+proj=laea +lat_0=45 +lon_0=-100 +x_0=0 +y_0=0 +ellps=sphere +units=m +no_defs") %>%
  ms_simplify()
```

```{r}
# Graph
ggplot() +
  geom_sf(data = simplified_cd114, mapping = aes(fill = voteshare_margin)) +
  scale_fill_gradient2(low = "skyblue3", mid = "white", high = "firebrick3", 
                         name = "Two-Party \nVoteshare Margin") +
  theme_void() +
  labs(title = "2014 Two-Party Vote-Share Margin by District")
```

