---
title: Blog 1
author: June Park
date: '2022-09-15'
slug: []
categories: []
tags: []
---

This week, I looked at the Republican/Democrat voteshare margin of House congressional elections. I analyzed the 2018 and 2014 congressional elections.

```{r}
# libraries
library(tidyverse)
library(ggplot2)
library(usmap)
library(rmapshaper)
library(sf)
library(blogdown)
```

```{r}
# data
housepartyvote <- read_csv("house party vote share by district 1948-2020.csv")
```

```{r}
# Dataset of 2018 voteshare margin
house2018 <- housepartyvote %>%
  filter(raceYear == 2018) %>%
  select(raceYear, State, district_num, district_id, RepVotes, DemVotes) %>%
  # summarize party vote share by state
  group_by(State) %>%
  # create Votemargin
  mutate(Votemargin = (sum(RepVotes - DemVotes))/sum(RepVotes + DemVotes)) %>%
  rename(state = State)

# Plot of 2018 voteshare margin
plot_usmap(data = house2018, 
           regions = "states", 
           values = "Votemargin",
           labels = TRUE) +
  scale_fill_gradient2(low = "skyblue3", 
                       mid = "white",
                       high = "firebrick3", 
                       name = "Two-party Voteshare Margin") +
  labs(title = "2018 Two-Party Voteshare Margin") +
  theme_void()
```